export const Routes = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  SUPER_BOL_2024: '/super-bol-2024',
  SIGN_UP_SUCCESS: '/sign-up/success',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_SUCCESS: '/forgot-password/success',
  RESET_PASSWORD_SUCCESS: '/reset-password/success',
  SET_PASSWORD_SUCCESS: '/set-password/success',
  CABINET: '/cabinet',
  PROFILE: '/cabinet/profile',
  PROFILE_APPLICATION: '/cabinet/participant/application',
  PROFILE_PARTICIPANTS: '/cabinet/participant/participants',
  PROFILE_PARTICIPANTS_PROFILES: '/cabinet/scout/participants',
  PROFILE_PARTICIPANTS_RATING: '/cabinet/scout/participants-rating',
  PROFILE_PARTICIPANTS_GROUPS: '/cabinet/scout/groups',
  PROFILE_NOTIFICATIONS: '/cabinet/participant/notifications',
  PROFILE_DOCUMENTS: '/cabinet/participant/documents',
  PROFILE_MODERATOR_PARTICIPANTS: '/cabinet/moder/participants',
  PROFILE_MODERATOR_STATS: '/cabinet/moder/stats',
  PROFILE_VOLUNTEER_SCANNER: '/cabinet/volunteer'
}