export const Routes = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  SIGN_UP_SUCCESS: '/sign-up/success',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_SUCCESS: '/forgot-password/success',
  RESET_PASSWORD_SUCCESS: '/reset-password/success',
  SET_PASSWORD_SUCCESS: '/set-password/success',
  CABINET: '/cabinet',
  PROFILE: '/cabinet/profile',
  PROFILE_APPLICATION: '/cabinet/application',
  PROFILE_PARTICIPANTS: '/cabinet/participants',
  PROFILE_PARTICIPANTS_PROFILES: '/cabinet/participants-profiles',
  PROFILE_NOTIFICATIONS: '/cabinet/notifications',
}